---
title: "In class 5"
author: "Ke Ke"
date: "11 May 2024"
date-modified: "last-modified"
format:
  html:
    code-fold: true
    code-tools: true
execute: 
  eval: true
  #echo: true display code chunk
  warning: false
  freeze: true
---

```{r}
pacman::p_load(tidyverse,readtext,quanteda,tidytext)
```

```{r}
setwd("C:/kekekay/ISSS608-VAA/inclass/inclass05/data")
```

```{r}
text_data <- readtext(paste0("MC1/articles","/*"))
#text_data <- readtext("MC1/articles/*")
```

```{r}
usenet_words <- text_data %>%   
  unnest_tokens(word, text) %>%   
  filter(str_detect(word, "[a-z']$"),        
         !word %in% stop_words$word)
```

```{r}
usenet_words %>%   count(word, sort = TRUE)
```

to split 'text_data' first column by using `tidyr` or `stringr`

```{r}
text_data_splitted <- text_data %>% 
  separate_wider_delim("doc_id",
                       delim = "__0__",
                       names = c("X","Y"),
                       too_few = "align_end")
```

```{r}
pacman::p_load(jsonlite,tidyverse)
```

```{r}
#setwd("C:/kekekay/ISSS608-VAA/inclass/inclass05/data")
mc1_data <- fromJSON("MC1/mc1.json")
```

instead of using igraph, we tend to use tidygraph
