project:
  type: website

website:
  title: "ISSS608-VAA"
  navbar:
    left:
    - text: "Hands-on Exercise"
      menu:
      - text: "Hands-on Exercise 1"
        href: "Hands_on_exercise/Hands_on_ex1/Hands_on_ex1.qmd"
      - text: "Hands-on Exercise 2"
        href: "Hands_on_exercise/Hands_on_ex2/Hands_on_ex2.qmd"
      - text: "Hands-on Exercise 3-1"
        href: "Hands_on_exercise/Hands_on_ex3/Hands-on_Ex03_1.qmd"
      - text: "Hands-on Exercise 3-2"
        href: "Hands_on_exercise/Hands_on_ex3/Hands-on_Ex03_2.qmd"
      - text: "Hands-on Exercise 4-1"
        href: "Hands_on_exercise/Hands_on_ex4/Hands-on_Ex04_1.qmd"
      - text: "Hands-on Exercise 4-2"
        href: "Hands_on_exercise/Hands_on_ex4/Hands-on_Ex04_2.qmd"
      - text: "Hands-on Exercise 4-3"
        href: "Hands_on_exercise/Hands_on_ex4/Hands-on_Ex04_3.qmd"
      - text: "Hands-on Exercise 5"
        href: "Hands_on_exercise/Hands_on_ex5/Hands-on_Ex05.qmd"
      - text: "Hands-on Exercise 6"
        href: "Hands_on_exercise/Hands_on_ex6/Hands-on_Ex06.qmd"
      - text: "Hands-on Exercise 7"
        href: "Hands_on_exercise/Hands_on_ex7/Hands-on_Ex07.qmd"  
        
        
    - text: "In-class Exercise"
      menu:
      - text: "In-class Exercise 1"
        href: "inclass/inclass01/inclass01.qmd"
      - text: "In-class Exercise 2"
        href: "inclass/inclass02/inclass02.qmd"
   
   
    - text: "Take-home Exercise"
      menu:
      - text: "Part I: Take-home Exercise 1:Singapore Private Residential Market"
        href: "takehome/takehome1.qmd"
      - text: "Part II: Take-home Exercise 1: Make-over"
        href: "takehome/takehome2.qmd"
      - text: "Part III: Take-home Exercise 2: Vast Challenge - MC3"
        href: "takehome/takehome3new.qmd"
    right: 
      - href: before_class.qmd
        text: Home
      - about.qmd

format:
  html:
    highlight-style: arrow
    theme: 
      light: journal
      dark: darkly
    css: styles.css
    toc: true

editor: visual

