project:
  type: website

website:
  title: "ISSS608-VAA"
  navbar:
    left:
    - text: "Hands-on Exercise"
      menu:
      - text: "Hands-on Exercise 1"
        href: "Hands_on_exercise/Hands_on_ex1/Hands_on_ex1.qmd"
    right: 
      - href: before_class.qmd
        text: Home
      - about.qmd

format:
  html:
    highlight-style: arrow
    theme: 
      light: journal
      dark: darkly
    css: styles.css
    toc: true

editor: visual

